### ISSUE TITLE
cloning error

### ISSUE THREAD

**Issue by aliiikz** [piyushsachdeva/GitLabCITutorial#1]
```shell
git clone -b develop  https://gitlab+deploy-token-497024:$TOKEN@gitlab.com/piyush.sachdeva055/myfirstproject.git
```
output
```shell
Cloning into 'myfirstproject'...
fatal: Authentication failed for 'https://gitlab+deploy-token-497024:@gitlab.com/piyush.sachdeva055/myfirstproject.git/'
```
there is no TOKEN for cloning the project, please make it public or add tell what the TOKEN is to set is as a variable
thnx

**Comment by piyushsachdeva** [comment]
Hi @aliiikz , 
Sorry for the late reply, Actually the project is public so, you should be able to clone without any token. Try removing the sample token and let me know if it worked?

Regards,
Piyush
